### PR TITLE
Automatic fetch for controller DB and public access to the addMappingFromFile function

### PR DESCRIPTION
**Pull request by WinterAlexander**
This PR introduces a script to fetch the SDL game controller database from it's latest version on build instead of keeping it's own separate version. This means the controller database will always be the most up to date whenever this library is compiled. Since it's now automatically generated instead of being kept, it's been removed from git and added as a gradle task that executes right before processing resources for the desktop sub module.

The mobile controllers are also stripped out of the file to remain consistent with the previous version which had it's mobile controllers stripped out. I needed to add a .gitkeep file to force the directory to stay present. Alternatively this directory could be created by the gradle task instead.

Finally, I added a simple access to the `addMappingsFromFile` in `JamepadControllerManager` making it now possible to add custom mappings without using reflection, on desktop only since `JamepadControllerManager` is only available on desktop anyway.

### CODE REVIEW

**Comment by WinterAlexander** [comment]
My PR for Nexilus GC adapter (#10) was merged in https://github.com/gabomdq/SDL_GameControllerDB btw, so it will be included in the db using this script from now on

**Review by MrStahlfelge — CHANGES_REQUESTED** [review]
`addMappingsFromFile` part is merged.

Fetching the new controller db file works when server is reachable. When not, it is not possible to build the lib and run the test project. This is because an existing db file is deleted first, then the db file download attempt is made afterwards. For better usability when no internet connection is present or GitHub's server is down (yes, that happened in the past), it would be better to first open the source URL. If that is not possible, either print a warning when there is an old db file, or an error when there is none.

**Comment by MrStahlfelge** [comment]
Another possible approach:
* delete the file on clean
* download the file only when it is not present

The gitkeep file could be avoided by letting Gradle create the directory.

**Comment by WinterAlexander** [comment]
Great suggestion. I went with the first approach as this approach updates the file most often, meaning every release of the library is guaranteed to deliver the most up to date database, even if you forget to update the script. This way it's also no longer a thing we need to think about while having to delete the file is a manual intervention.

Also made the script create the directory and so removed the .gitkeep

Added 2 lines of logging, one of which is info (and thus not visible by default) and the other warn of it not being able to update the DB if internet is down or if github is down.

**Comment by MrStahlfelge** [comment]
> meaning every release of the library is guaranteed to deliver the most up to date database, even if you forget to update the script

That's nothing to worry about. Releases are done by GitHub Actions within a clean container.

**Comment by WinterAlexander** [comment]
I see well it's really only a matter of preference at this point. This new version doesn't even delete the file, just overwrites it. We can delete it on clean if you want to and set the task as up to date when the file is present.

**Comment by MrStahlfelge** [comment]
It is fine for me the way it is, just one thing left now:

> If that is not possible, either print a warning when there is an old db file, or an error when there is none.

It now prints a warning when there is an old db file and works as intended, but when there is no db file present it also just prints a warning and continues. I would suggest to have an error here just in case the file is not present at its current place in the future any more, so that a release fails when there is not a file available at all.

**Comment by WinterAlexander** [comment]
Yes that is a good point. Now  throwing the error when there is no file

**Review by MrStahlfelge — APPROVED** [review]
Cool feature, thank you

**Pull request merged**
