### PR TITLE
Fixed gamecontrollerdb.txt failing to load with packr

### PR DESCRIPTION
**Pull request by WinterAlexander**
Fixed issue #13 by adding the slash at the beginning of the mapping file, which is needed for proper loading of the classpath resource.

### CODE REVIEW

**Comment by WinterAlexander** [comment]
For convenience, we could improve jamepad and make it so `manager.addMappingsFromFile("myfile.txt")` automatically prepends a slash if missing one. It currently isn't clear to the user that this slash is needed for it to work and we could just make it not required for convenience. This would be a relatively easy change but would have to be made in https://github.com/libgdx/Jamepad (or simply be added in the wrapper function `JamepadControllerManager#addMappingsFromFile` instead). Please let me know what are your thoughts on this suggestion.

**Comment by MrStahlfelge** [comment]
I would not like to change jamepad to add the slash, this might be wrong if someone really wants to load a file from the filesystem.
About the change, why not use Jamepad's default constructor and omit defining an own mappingsPath?

**Comment by WinterAlexander** [comment]
> I would not like to change jamepad to add the slash, this might be wrong if someone really wants to load a file from the filesystem.
> About the change, why not use Jamepad's default constructor and omit defining an own mappingsPath?

Note that Jamepad's code does the loading from `getResourceAsStream` (classpath) so it will always need a slash at the beginning of paths. It could offer functionalities to load files from the filesystem but it does not right now. There is no situation where this function in Jamepad wouldn't need a slash at the beginning of paths.

Sure we could just call the default constructor instead, I have no idea why this path was redefined anyway.

**Review by MrStahlfelge — APPROVED** [review]
LGTM and works

**Pull request merged**
