### PR TITLE
upgrade robovm to 2.3.19

### LINKED ISSUE #34: Incompatible with RoboVM 2.3.19
Gdx-Controllers is currently incompatible with RoboVM 2.3.19. Using Gdx-Controllers 2.2.3 with RoboVM 2.3.19 will yield the following exception: 

> java.lang.NoSuchMethodError: org.robovm.apple.gamecontroller.GCController$Notifications.observeDidConnect(Lorg/robovm/objc/block/VoidBlock1;)Lorg/robovm/apple/foundation/NSObjectProtocol;
 at com.badlogic.gdx.controllers.IosControllerManager.initializeControllerArray(IosControllerManager.java:86)

Due to the following changes in RoboVM: https://github.com/MobiVM/robovm/pull/683

MobiVM/RoboVM dependency needs to be upgraded to 2.3.19 to resolve this.

### PR DESCRIPTION
**Pull request by klianc09**
This fixes #34.

Also upgraded the robovm gradle plugin to match the robovm version (2.3.19)
I also upgraded libGDX to the newest version (1.11.0), IDK if that's okay.
I saw in `test/lwjgl3/build.gradle` there is a comment relating to libGdx versions not sure if that's relevant.

Only thing I did test or verify was:

- execute `./gradlew clean uploadArchives -PLOCAL=true` like it says in the readme (builds successfully)
- used my locally build snapshot artifact in my game to verify that the error in #34 no longer shows up (error no longer shows up)

### CODE REVIEW

**Comment by klianc09** [comment]
Alright, now also made sure the test projects build without errors, verifying the gradle commands from the workflow file build successful

Only needed to remove one dependency from the android test project (natives-armeabi)

Then saw that for some reason two .so files were checked in and were registered as being changed. I added them to the gitignore, because it looks like an oversight to me that they aren't. Feel free to correct me.

**Comment by MrStahlfelge** [comment]
We should not raise the gdx version when not needed as this makes the lib unusable for this versions (without further gradle hacking). Everything else is fine!

**Comment by klianc09** [comment]
Alright, should I just add another commit, or clean up the history? I'm not sure, can I just change the history of a pull request, or do I need to make a new one?

**Comment by MrStahlfelge** [comment]
Just make a new commit, we can squash merge

**Comment by klianc09** [comment]
alright undid the libgdx version upgrade

**Review by MrStahlfelge — APPROVED** [review]

**Pull request merged**
